server.port: ${services.pricing.port}

spring.datasource.url: jdbc:h2:mem:pricing;MODE=PostgreSQL

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      group-id: pricing
#    producer:
#      bootstrap-servers: 127.0.0.1:9092

#spring:
#  kafka:
#    bootstrap-servers: localhost:19091
#    consumer:
#      auto-offset-reset: earliest
#      group-id: bottega
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#
#test:
#  topic: pricing.price