name: Sales CI
run-name: Sales CI

on:
  push:
    paths:
      - 'services/Sales/**'
      - 'libs/SharedLib/**'
      - '.github/workflows/ci-pricing.yml'
      - '.github/workflows/ci-shared-lib.yml'
  workflow_dispatch:
  repository_dispatch:
    types: [ sales-ci-webhook ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Configure Gradle for optimal use in GiHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Test
        run: >-
          cd services/Sales &&
          ./gradlew 
          test

  dev-deployment:
    if: ${{ github.ref_name == 'main' }}
    needs: build
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Dev
        run: echo "Deploying to dev"

  prod-deployment:
    if: ${{ github.ref_name == 'main' }}
    needs: dev-deployment
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to prod
        run: echo "Deploying to prod"
